version: "3.9"
services:
  composer:
    image: composer
    volumes:
      - ./wordpress/:/app
    command: install
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./wordpress:/var/www/wordpress
    ports:
      - 80:80
  php:
    build: ./php
    restart: always
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./wordpress/vendor:/var/www/vendor
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'SendPie44544541!'
      MYSQL_DATABASE: 'johndinhdev'
      MYSQL_USER: 'john'
      MYSQL_PASSWORD: 'cody4454'
