version: "3.9"
services:
  composer:
    image: composer
    volumes:
      - ./wordpress/:/app
    command: install
  ftp:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./wordpress/web:/home/ftpusers"
      - "./ftp/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: "ftpusers"
      FTP_USER_PASS: "cody4454"
      FTP_USER_HOME: "/home/ftpusers"
      FTP_USER_UID: 33
      FTP_USER_GID: 33
    restart: always
  nginx:
    build: ./nginx
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./wordpress:/var/www/wordpress
    ports:
      - "${PORT}:80"
  php:
    build: ./php
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./wordpress/vendor:/var/www/vendor
  db:
    image: mariadb
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
