version: "3.9"
services:
  composer:
    image: composer
    volumes:
      - ./wordpress/:/app
    command: install
  nginx:
    build: ./nginx
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./wordpress:/var/www/wordpress
    ports:
      - "${PORT}:80"
  php:
    build: ./php
    restart: always
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./wordpress/vendor:/var/www/vendor
  db:
    image: mariadb
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
