version: "3.9"
services:
  composer:
    image: composer
    volumes:
      - ./wordpress/:/app
    command: install
  ftp:
    image: stilliard/pure-ftpd:hardened
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: "wordpress"
      FTP_USER_PASS: "password"
      FTP_USER_HOME: "/home/wordpress"
      FTP_USER_UID: 33
      FTP_USER_GID: 33
    volumes:
      - "./wordpress/web:/home/wordpress"
      - "./ftp/passwd:/etc/pure-ftpd/passwd"
    ports:
      - target: 21
        published: 21
        protocol: tcp
        mode: host

    # Bind each passive ports to the host
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host
  nginx:
    build: ./nginx
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./wordpress:/var/www/wordpress
    ports:
      - "${PORT}:80"
  php:
    build: ./php
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./wordpress/vendor:/var/www/vendor
  db:
    image: mariadb
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
